name: deploy spot2

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: root        
          MYSQL_DATABASE: spot2           
          MYSQL_USER: ci_user             
          MYSQL_PASSWORD: ci_password
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress --no-suggest

      - name: Copy .env.example to .env
        run: cp .env.example .env

      - name: Update .env for CI
        run: |
          sed -i 's/DB_CONNECTION=mysql/DB_CONNECTION=mysql/' .env
          sed -i 's/DB_HOST=127.0.0.1/DB_HOST=127.0.0.1/' .env
          sed -i 's/DB_PORT=3306/DB_PORT=3306/' .env
          sed -i 's/DB_DATABASE=spot2/DB_DATABASE=spot2/' .env
          sed -i 's/DB_USERNAME=root/DB_USERNAME=ci_user/' .env
          sed -i 's/DB_PASSWORD=/DB_PASSWORD=ci_password/' .env

      - name: Wait for MySQL to be ready
        run: sleep 10

      - name: Verify MySQL Connection
        run: |
          mysql -h 127.0.0.1 -u ci_user -pci_password -e "SHOW DATABASES;"

      - name: Generate application key
        run: php artisan key:generate

      - name: Run migrations
        run: php artisan migrate --force

      - name: Run tests
        run: php artisan test