name: deploy spot2

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress --no-suggest

      - name: Copy .env.example to .env
        run: cp .env.example .env

      - name: Generate application key
        run: php artisan key:generate

      - name: Deploy to EC2
        run: |
            git pull origin main
            php artisan migrate --force
            php artisan config:cache
            php artisan route:cache
            php artisan view:cache
            sudo systemctl restart httpd
          EOF
          
      - name: Create database
        run: |
          sudo mysql -e 'CREATE DATABASE testing;'
          php artisan migrate --env=testing --database=testing

      - name: Run tests
        run: php artisan test --env=testing --database=testing

